def get_foods_json():
    return foods_json


foods_json = {
    "foods": [
        {"name": "Chicken Breast", "calories": 165, "protein": 31},
        {"name": "Salmon", "calories": 208, "protein": 20},
        {"name": "Egg", "calories": 155, "protein": 13},
        {"name": "Tofu", "calories": 76, "protein": 8},
        {"name": "Almonds", "calories": 579, "protein": 21},
        {"name": "Brown Rice", "calories": 112, "protein": 2.6},
        {"name": "Oats", "calories": 389, "protein": 17},
        {"name": "Greek Yogurt", "calories": 59, "protein": 10},
        {"name": "Cheddar Cheese", "calories": 403, "protein": 25},
        {"name": "Lentils", "calories": 116, "protein": 9},
        {"name": "Sweet Potato", "calories": 86, "protein": 1.6},
        {"name": "Spinach", "calories": 23, "protein": 2.9},
        {"name": "Broccoli", "calories": 55, "protein": 3.7},
        {"name": "Avocado", "calories": 160, "protein": 2},
        {"name": "Beef (Lean)", "calories": 250, "protein": 26},
        {"name": "Pork (Lean)", "calories": 242, "protein": 27},
        {"name": "Shrimp", "calories": 99, "protein": 24},
        {"name": "Tuna", "calories": 132, "protein": 28},
        {"name": "Cod", "calories": 82, "protein": 18},
        {"name": "Turkey Breast", "calories": 135, "protein": 30},
        {"name": "Cottage Cheese", "calories": 98, "protein": 11},
        {"name": "Peanut Butter", "calories": 588, "protein": 25},
        {"name": "Quinoa", "calories": 120, "protein": 4.1},
        {"name": "Chickpeas", "calories": 164, "protein": 8.9},
        {"name": "Kidney Beans", "calories": 127, "protein": 8.7},
        {"name": "Apple", "calories": 52, "protein": 0.3},
        {"name": "Banana", "calories": 96, "protein": 1.3},
        {"name": "Orange", "calories": 47, "protein": 0.9},
        {"name": "Strawberries", "calories": 32, "protein": 0.7},
        {"name": "Blueberries", "calories": 57, "protein": 0.7},
        {"name": "Watermelon", "calories": 30, "protein": 0.6},
        {"name": "Pineapple", "calories": 50, "protein": 0.5},
        {"name": "Mango", "calories": 60, "protein": 0.8},
        {"name": "Carrot", "calories": 41, "protein": 0.9},
        {"name": "Tomato", "calories": 18, "protein": 0.9},
        {"name": "Cucumber", "calories": 15, "protein": 0.7},
        {"name": "Zucchini", "calories": 17, "protein": 1.2},
        {"name": "Eggplant", "calories": 25, "protein": 1},
        {"name": "Mushrooms", "calories": 22, "protein": 3.1},
        {"name": "Cauliflower", "calories": 25, "protein": 1.9},
        {"name": "Bell Peppers", "calories": 31, "protein": 1},
        {"name": "Asparagus", "calories": 20, "protein": 2.2},
        {"name": "Green Beans", "calories": 31, "protein": 1.8},
        {"name": "Potato", "calories": 77, "protein": 2},
        {"name": "Onion", "calories": 40, "protein": 1.1},
        {"name": "Garlic", "calories": 149, "protein": 6.4},
        {"name": "Hummus", "calories": 166, "protein": 8},
        {"name": "Pumpkin Seeds", "calories": 559, "protein": 30},
        {"name": "Sunflower Seeds", "calories": 584, "protein": 21},
        {"name": "Chia Seeds", "calories": 486, "protein": 17},
        {"name": "Flax Seeds", "calories": 534, "protein": 18},
        {"name": "Walnuts", "calories": 654, "protein": 15},
        {"name": "Cashews", "calories": 553, "protein": 18},
        {"name": "Hazelnuts", "calories": 628, "protein": 15},
        {"name": "Pecans", "calories": 691, "protein": 9},
        {"name": "Macadamia Nuts", "calories": 718, "protein": 8},
        {"name": "Pistachios", "calories": 562, "protein": 20},
        {"name": "Raspberries", "calories": 52, "protein": 1.2},
        {"name": "Blackberries", "calories": 43, "protein": 1.4},
        {"name": "Cranberries", "calories": 46, "protein": 0.4},
        {"name": "Grapes", "calories": 69, "protein": 0.6},
        {"name": "Pear", "calories": 57, "protein": 0.4},
        {"name": "Plum", "calories": 46, "protein": 0.7},
        {"name": "Apricot", "calories": 48, "protein": 1.4},
        {"name": "Kiwi", "calories": 61, "protein": 1.1},
        {"name": "Peach", "calories": 39, "protein": 0.9},
        {"name": "Nectarine", "calories": 44, "protein": 1},
        {"name": "Papaya", "calories": 43, "protein": 0.5},
        {"name": "Dates", "calories": 277, "protein": 1.8},
        {"name": "Prunes", "calories": 240, "protein": 2.2},
        {"name": "Raisins", "calories": 299, "protein": 3.1},
        {"name": "Coconut", "calories": 354, "protein": 3.3},
        {"name": "Pomegranate", "calories": 83, "protein": 1.7},
        {"name": "Lychee", "calories": 66, "protein": 0.8},
        {"name": "Guava", "calories": 68, "protein": 2.6},
        {"name": "Passion Fruit", "calories": 97, "protein": 2.2},
        {"name": "Durian", "calories": 147, "protein": 1.5},
        {"name": "Jackfruit", "calories": 95, "protein": 1.7},
        {"name": "Cantaloupe", "calories": 34, "protein": 0.8},
        {"name": "Honeydew", "calories": 36, "protein": 0.5},
        {"name": "Fig", "calories": 74, "protein": 0.8},
        {"name": "Persimmon", "calories": 70, "protein": 0.6},
        {"name": "Carob", "calories": 222, "protein": 4.6},
        {"name": "Barley", "calories": 354, "protein": 12},
        {"name": "Buckwheat", "calories": 343, "protein": 13},
        {"name": "Millet", "calories": 378, "protein": 11},
        {"name": "Farro", "calories": 340, "protein": 14},
        {"name": "Amaranth", "calories": 371, "protein": 14},
        {"name": "Seitan", "calories": 120, "protein": 21},
        {"name": "Tempeh", "calories": 195, "protein": 19},
        {"name": "Edamame", "calories": 121, "protein": 11},
        {"name": "Soy Milk", "calories": 54, "protein": 3.3},
        {"name": "Almond Milk", "calories": 17, "protein": 0.6},
        {"name": "Coconut Milk", "calories": 230, "protein": 2.3},
        {"name": "Rice Milk", "calories": 47, "protein": 0.3},
        {"name": "Hemp Seeds", "calories": 567, "protein": 31}
    ]
}
